# Development setup with hot reload
# Use this for local development

services:
  # Neo4j Graph Database
  neo4j:
    image: neo4j:5-community
    container_name: citation-neo4j-dev
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD}
      - NEO4J_dbms_memory_pagecache_size=256M
      - NEO4J_dbms_memory_heap_max__size=256M
    volumes:
      - neo4j_dev_data:/data
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: citation-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped

  # Backend with hot reload
  backend:
    build:
      context: ./backend
      target: development
    container_name: citation-backend-dev
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
    depends_on:
      - neo4j
      - redis
    restart: unless-stopped

volumes:
  neo4j_dev_data:
  redis_dev_data:
