services:
  # Neo4j Graph Database
  neo4j:
    image: neo4j:5-community
    container_name: citation-neo4j
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_max__size=512M
    volumes:
      - neo4j_data:/data

  # Redis Cache (Optional)
  redis:
    image: redis:7-alpine
    container_name: citation-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  neo4j_data:
  redis_data: