version: '3.8'

x-common-environment: &common-env
  NEO4J_URI: bolt://neo4j:7687
  NEO4J_USER: neo4j
  REDIS_URL: redis://redis:6379/0
  CELERY_BROKER_URL: redis://redis:6379/1
  CELERY_RESULT_BACKEND: redis://redis:6379/2

services:
  # FastAPI Application - Development Profile
  api-dev:
    build: 
      context: .
      target: development
    ports:
      - "8000:8000"
    environment:
      <<: *common-env
      DEBUG: true
      ENVIRONMENT: development
      NEO4J_PASSWORD: dev_password
      SECRET_KEY: dev-secret-key-at-least-32-characters-long
      SESSION_SECRET: dev-session-secret-here
      OPENALEX_EMAIL: ${OPENALEX_EMAIL:-demo@example.com}
    depends_on:
      - neo4j
      - redis
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    profiles: ["dev"]
    networks:
      - citation-network

  # FastAPI Application - Production Profile
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      <<: *common-env
      DEBUG: false
      ENVIRONMENT: production
      NEO4J_PASSWORD: ${NEO4J_PASSWORD:-your_neo4j_password}
      SECRET_KEY: ${SECRET_KEY:-your-super-secret-key-here-at-least-32-characters-long}
      SESSION_SECRET: ${SESSION_SECRET:-your-session-secret-here}
    depends_on:
      - neo4j
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    profiles: ["prod"]
    networks:
      - citation-network

  # Neo4j Database
  neo4j:
    image: neo4j:5.15-community
    ports:
      - "7474:7474"  # HTTP Browser
      - "7687:7687"  # Bolt Protocol
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD:-dev_password}
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_memory_heap_initial__size: 512M
      NEO4J_dbms_memory_heap_max__size: 1G
      NEO4J_dbms_memory_pagecache_size: 512M
    volumes:
      - neo4j_data:/data
    restart: unless-stopped
    networks:
      - citation-network

  # Redis Cache & Message Broker
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - citation-network

  # Redis Commander (Development tool)
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    profiles: ["dev"]
    networks:
      - citation-network

volumes:
  neo4j_data:
  redis_data:

networks:
  citation-network:
    driver: bridge